name: Backend CI

on:
    - pull_request

jobs:
    tests:
        name: Python tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Install requirements.txt dependencies with pip
              run: |
                  python -m pip install -e .

            - name: Run posthog tests
              env:
                  SECRET_KEY: '6b01eee4f945ca25045b5aab440b953461faf08693a9abbf1166dc7c6b9772da' # unsafe - for testing only
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
              run: |
                  python setup.py test
            - name: Run EE tests
              env:
                  SECRET_KEY: '6b01eee4f945ca25045b5aab440b953461faf08693a9abbf1166dc7c6b9772da' # unsafe - for testing only
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
                  PRIMARY_DB: 'clickhouse'
                  CLICKHOUSE_HOST: 'localhost'
                  CLICKHOUSE_DATABASE: 'posthog_test'
                  CLICKHOUSE_SECURE: 'False'
                  CLICKHOUSE_VERIFY: 'False'
              run: |
                  mkdir -p frontend/dist
                  touch frontend/dist/index.html
                  touch frontend/dist/layout.html
                  touch frontend/dist/shared_dashboard.html
                  python manage.py test ee --testrunner="ee.clickhouse.clickhouse_test_runner.ClickhouseTestRunner"
